project:
  type: website
  output-dir: docs

website:
  title: "Proyecto Final"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: data_cleaning.qmd
        text: Limpieza y Preprocesamiento
      - href: visualizations.qmd
        text: Visualización de Datos 
format:
  html:
    theme: cosmo
    toc: true